import type { Metadata } from "next";
import "./styles/globals.css";
import { Header } from "@/widgets/Header";
import { montserrat, raleway, roboto } from '@/shared/lib/fonts';
import { Toaster } from "@/shared/ui";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body
				className={`${montserrat.variable} ${raleway.variable} ${roboto.variable} antialiased`}
			>
				<Providers>
					<Toaster />
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
}
